ser_notes_note_type:
    resource: "@SerNotesBundle/Controller/NoteTypeController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

notes_show:
    resource: "@SerNotesBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"