<?php

namespace SerNotesBundle\Repository;

/**
 * NoteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNoteTypeByNames()
    {
        return $this->createQueryBuilder('note_type')
            ->orderBy('note_type.name','ASC');
    }
}
